Train Begin...
Episodes:   0%|                                                 | 0/1000 [00:00<?, ?it/s]/home/js/DAA_CPS/Agent.py:102: UserWarning: Using a target size (torch.Size([64])) that is different to the input size (torch.Size([960])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  self.loss = F.smooth_l1_loss(current_q.squeeze(), target_q)   | 0/3600 [00:00<?, ?it/s]
Prev (5, 3)
Next (5, 12)
Prev (10, 3)
Next (10, 12)
Prev (18, 92)
Next (24, 92)
Prev (75, 3)
Next (75, 12)
Prev (95, 3)
Next (95, 12)
Prev (55, 3)
Next (55, 12)
Prev (98, 19)
Next (85, 19)
Prev (85, 3)
Next (85, 12)
Prev (46, 77)
Next (46, 72)
Prev (43, 77)
Next (43, 72)
Prev (4, 82)
Next (4, 74)
Prev (1, 33)
Next (11, 33)
Prev (28, 98)
Next (24, 98)
Prev (18, 89)
Next (24, 89)
Prev (66, 62)
Next (66, 69)
Episodes:   0%|                                                 | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):                                                       
  File "/home/js/DAA_CPS/train.py", line 111, in <module>
    train(config)
  File "/home/js/DAA_CPS/train.py", line 71, in train
    agent.replay(batch_size)
  File "/home/js/DAA_CPS/Agent.py", line 102, in replay
    self.loss = F.smooth_l1_loss(current_q.squeeze(), target_q)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/js/anaconda3/envs/DAA_CPS/lib/python3.12/site-packages/torch/nn/functional.py", line 3684, in smooth_l1_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/js/anaconda3/envs/DAA_CPS/lib/python3.12/site-packages/torch/functional.py", line 76, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (960) must match the size of tensor b (64) at non-singleton dimension 0
